### ISSUE TITLE
Cannot run Pelican on Mac OS Yosemite

### ISSUE THREAD

**Issue by drpaneas** [getpelican/pelican#1558]
I have installed Python via brew.

drpaneas@macbook:~$ pelican

Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 7, in <module>
    from pelican import main
  File "/Library/Python/2.7/site-packages/pelican/__init__.py", line 20, in <module>
    from pelican.generators import (ArticlesGenerator, PagesGenerator,
  File "/Library/Python/2.7/site-packages/pelican/generators.py", line 23, in <module>
    from pelican.readers import Readers
  File "/Library/Python/2.7/site-packages/pelican/readers.py", line 24, in <module>
    from six.moves.html_parser import HTMLParser
ImportError: No module named html_parser

**Comment by barrysteyn** [comment]
No, the problem is... `If you get the ImportError “No module named HTMLParser”, your problem is that you’re running the Python 2 version of the code under Python 3.`  This taken from the [beautiful soup errors after installation](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#problems-after-installation) page.

This seems to be a problem with Yosemite (don't ask me how this happens). But there is an easy fix: Just install things using virtualenv.

@justinmayer This problem seems to crop up over the internet all the time regarding Pelican. Perhaps a note in the documentation somewhere. I can help if desired, but I don't know why the pelican for python3 is getting selected.

**Comment by Craiglea** [comment]
That sounds like exactly the problem I have when I upgraded to 3.5 earlier this week (while a little voice in my head was whispering "if it ain't broke don't fix it".

I've tried repeating the upgrade using a virtualenv but still get the following problems:

      File "/usr/local/bin/pelican", line 7, in <module>
          from pelican import main
        File "/Library/Python/2.7/site-packages/pelican/__init__.py", line 20, in <module>
          from pelican.generators import (ArticlesGenerator, PagesGenerator,
        File "/Library/Python/2.7/site-packages/pelican/generators.py", line 23, in <module>
          from pelican.readers import Readers
        File "/Library/Python/2.7/site-packages/pelican/readers.py", line 24, in <module>
          from six.moves.html_parser import HTMLParser
      ImportError: No module named html_parser
      make: *** [html] Error 1

Any help would be welcome.
