### ISSUE TITLE
Pelican confused about site-packages structure

### ISSUE THREAD

**Issue by hydrogen18** [getpelican/pelican#1574]
Pelican seems to be very confused about the site-packages structure of Python. It is trying to treat the '.egg' file as a directory

```
ericu@archimedes:~$ pelican
Traceback (most recent call last):
  File "/home/ericu/local/bin/pelican", line 9, in <module>
    load_entry_point('pelican==3.5.0', 'console_scripts', 'pelican')()
  File "/home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican/__init__.py", line 351, in main
  File "/home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican/__init__.py", line 337, in get_instance
  File "/home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican/settings.py", line 173, in read_settings
  File "/home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican/settings.py", line 224, in configure_settings
Exception: Could not find the theme /home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican/themes/notmyidea
ericu@archimedes:~$ pelican-themes --install /home/ericu/builds/pelican-themes/notmyidea-cms
notmyidea-cms/    notmyidea-cms-fr/ 
ericu@archimedes:~$ pelican-themes --install /home/ericu/builds/pelican-themes/notmyidea-cms
Cannot copy `/home/ericu/builds/pelican-themes/notmyidea-cms' to `/home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican/themes/notmyidea-cms':
[Errno 20] Not a directory: '/home/ericu/local/lib/python2.7/site-packages/pelican-3.5.0-py2.7.egg/pelican'
```

**Comment by justinmayer** [comment]
Hi Eric. Were you able to resolve your problem?

**Comment by hydrogen18** [comment]
I ended up just pulling master and reset'ing my HEAD to a much older commit. I will pull down the latest version soon and give it another try.

**Comment by justinmayer** [comment]
Please comment here if the issue persists. Thanks!
