### ISSUE TITLE
Python 3.4 processing of content results in CRITICAL: unorderable types: Article() < Article()

### ISSUE THREAD

**Issue by mfa** [getpelican/pelican#1591]
Python 3.4.0 on Ubuntu 14.10

running pelican:
``
pelican content -s publishconf.py 
``

results in:
``
CRITICAL: unorderable types: Article() < Article()
``

after deleting of all articles except one, the publishing works.

Any hint how to fix this problem?

**Comment by avaris** [comment]
Need more detail. Can you run it with `--debug`? That should give a full traceback.

**Comment by ingwinlu** [comment]
add the content of your `publishconf` and `pelicanconf` as well just to be sure

**Comment by mfa** [comment]
sorry for my late response.

I narrowed it down to the theme.
With the default theme the problem doesn't exists.

To reproduce the problem I made a fresh pelican installation with two articles (with one article there is no error).
my test pelican is in: https://github.com/mfa/pelican-article-critical

**Comment by mfa** [comment]
--debug Traceback:
```
Traceback (most recent call last):
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/__init__.py", line 425, in main
    pelican.run()
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/__init__.py", line 175, in run
    p.generate_output(writer)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/generators.py", line 600, in generate_output
    self.generate_pages(writer)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/generators.py", line 477, in generate_pages
    self.generate_direct_templates(write)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/generators.py", line 425, in generate_direct_templates
    page_name=os.path.splitext(save_as)[0])
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/writers.py", line 212, in write_file
    override_output)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/pelican/writers.py", line 156, in _write_file
    output = template.render(localcontext)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/jinja2/_compat.py", line 36, in reraise
    raise value.with_traceback(tb)
  File "/home/mfa/git/pelican-article-critical/themes/zurb-F5-basic/templates/tags.html", line 1, in <module>
    {% extends "base.html" %}
  File "/home/mfa/git/pelican-article-critical/themes/zurb-F5-basic/templates/base.html", line 53, in <module>
    {% block content %}{% endblock %}
  File "/home/mfa/git/pelican-article-critical/themes/zurb-F5-basic/templates/tags.html", line 8, in <module>
    {% for article in articles|sort %}
  File "/home/mfa/.virtualenvs/34599392d0bbf0a0/lib/python3.4/site-packages/jinja2/filters.py", line 265, in do_sort
    return sorted(value, key=sort_func, reverse=reverse)
TypeError: unorderable types: Article() < Article()
```

**Comment by ingwinlu** [comment]
i don't know why that theme would need to sort articles (they are sorted by publishing date in that context).

if you really want to use that theme, just delete the | sort on the breaking line in tags.html and mention it to the maintainer of the theme.

this is not a pelican issue.

**Comment by mfa** [comment]
True.
after removing the sort in the theme everything works.

For future reference: Don't use sort in templates on articles.
