### ISSUE TITLE
pelican-quickstart crashes on setting timezone

### ISSUE THREAD

**Issue by bjo81** [getpelican/pelican#1695]
> What is your time zone? [Europe/Paris] 
Traceback (most recent call last):
  File "/usr/bin/pelican-quickstart", line 9, in <module>
    load_entry_point('pelican==3.5.0', 'console_scripts', 'pelican-quickstart')()
  File "/usr/lib/python3.4/site-packages/pelican/tools/pelican_quickstart.py", line 225, in main
    CONF['timezone'] = ask_timezone('What is your time zone?', CONF['timezone'], _TZ_URL)
  File "/usr/lib/python3.4/site-packages/pelican/tools/pelican_quickstart.py", line 170, in ask_timezone
    r = pytz.all_timezones[lower_tz.index(r)]
AttributeError: 'map' object has no attribute 'index'

Version: 3.5.0.r112.g249a919-1, OS: Archlinux

**Comment by ingwinlu** [comment]
your pytz version?

**Comment by bjo81** [comment]
2014.10-1
