### ISSUE TITLE
'pelican.contents.Page object' has no attribute 'index'

### ISSUE THREAD

**Issue by stevengorrell** [getpelican/pelican#1721]
Created a test page:

```
Title: Page One
Date: 2015-05-14 08:00
Slug: page-one
Authors: Steven
   
Blah
```

Pelican compiles fine.

Create an additional page.

```
Title: Page Two
Date: 2015-05-14 07:00
Slug: page-two 
Authors: Steven

blah
```

Pelican fails to compile:

```
CRITICAL: 'pelican.contents.Page object' has no attribute 'index'
Traceback (most recent call last):
  File "C:\Python27\Scripts\pelican-script.py", line 9, in <module>
    load_entry_point('pelican==3.5.0', 'console_scripts', 'pelican')()
  File "c:\python27\src\pelican\pelican\__init__.py", line 462, in main
    pelican.run()
  File "c:\python27\src\pelican\pelican\__init__.py", line 177, in run
    p.generate_output(writer)
  File "c:\python27\src\pelican\pelican\generators.py", line 601, in generate_output
    self.generate_pages(writer)
  File "c:\python27\src\pelican\pelican\generators.py", line 477, in generate_pages
    self.generate_articles(write)
  File "c:\python27\src\pelican\pelican\generators.py", line 355, in generate_articles
    blog=True)
  File "c:\python27\src\pelican\pelican\writers.py", line 211, in write_file
    override_output)
  File "c:\python27\src\pelican\pelican\writers.py", line 155, in _write_file
    output = template.render(localcontext)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\src\pelican\pelican\themes\foundation-default-colours\templates\article.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "c:\python27\src\pelican\pelican\themes\foundation-default-colours\templates\base.html", line 118, in top-level template code
    {% for pg in PAGES | sort(attribute='index') %}
  File "C:\Python27\lib\site-packages\jinja2\filters.py", line 265, in do_sort
    return sorted(value, key=sort_func, reverse=reverse)
jinja2.exceptions.UndefinedError: 'pelican.contents.Page object' has no attribute 'index'
```

**Comment by ingwinlu** [comment]
read the trace
`{% for pg in PAGES | sort(attribute='index') %}`
your theme demands an index attribute, yet you don't provide one, not a pelican issue

**Comment by stevengorrell** [comment]
Thanks for pointing that out. Adding Index: XX as metatdata on each page worked.
