### ISSUE TITLE
AttributeError: 'Tag' object has no attribute '_slug'

### ISSUE THREAD

**Issue by ionelmc** [getpelican/pelican#1722]
I'm playing with the master (8786732) a bit but I get this:
```
WARNING: Caught exception "'Tag' object has no attribute '_slug'". Reloading.
  |___
  | Traceback (most recent call last):
  |   File "c:\users\ionel_000\projects\pelican\pelican\__init__.py", line 437, in main
  |     pelican.run()
  |   File "c:\users\ionel_000\projects\pelican\pelican\__init__.py", line 169, in run
  |     p.generate_context()
  |   File "c:\users\ionel_000\projects\pelican\pelican\generators.py", line 546, in generate_context
  |     self.tags[tag].append(article)
  |   File "c:\users\ionel_000\projects\pelican\pelican\urlwrappers.py", line 53, in __hash__
  |     return hash(self.slug)
  |   File "c:\users\ionel_000\projects\pelican\pelican\urlwrappers.py", line 35, in slug
  |     if self._slug is None:
  | AttributeError: 'Tag' object has no attribute '_slug'
```

**Comment by ingwinlu** [comment]
can you provide more info that might be relevant? configs/content/etc. you know the drill.

**Comment by ionelmc** [comment]
Ooops, I thought it was some known-ish issue. Turns out I had cache on and the old cache unpickled uncompatible stuff. 

Worth documenting in the next release notes I suppose?

**Comment by ionelmc** [comment]
Or maybe have a "version" attribute/field/something in the cache files?

**Comment by ionelmc** [comment]
PS. I have `CONTENT_CACHING_LAYER = 'reader'` in the settings

**Comment by justinmayer** [comment]
Documented this in the upgrade notes at the bottom of the [release announcement](http://blog.getpelican.com/pelican-3.6-released.html).
