### ISSUE TITLE
Automatically choose an open port

### ISSUE THREAD

**Issue by moorepants** [getpelican/pelican#1839]
If you want to have more that one pelican site running locally on port 8000 (or you are using port 8000 for something else), it would be nice if pelican just chose a different port, e.g. 8001 instead of failing. This is the current error:

```
Done: Processed 0 articles, 0 drafts, 5 pages and 16 hidden pages in 1.40 seconds.
Traceback (most recent call last):
  File "/home/moorepants/miniconda/envs/pelican/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/moorepants/miniconda/envs/pelican/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/moorepants/miniconda/envs/pelican/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/moorepants/Websites/eme150a-website/fabfile.py", line 64, in reserve
    serve()
  File "/home/moorepants/Websites/eme150a-website/fabfile.py", line 56, in serve
    server = AddressReuseTCPServer(('', PORT), ComplexHTTPRequestHandler)
  File "/home/moorepants/miniconda/envs/pelican/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/home/moorepants/miniconda/envs/pelican/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/home/moorepants/miniconda/envs/pelican/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```

**Comment by justinmayer** [comment]
Hi Jason. Is this something you would like to work on?

**Comment by moorepants** [comment]
No, not in particular. But if I ever have a spare cycle I may look into solving it. Is this something you'd accept a patch for?

**Comment by sevagh** [comment]
In C you can bind port 0 to let the OS allocate a port for you. Is that a better solution than having a list of ports and cycling through them, or incrementing up from 8000?

**Comment by Scheirle** [comment]
@sevagh I think binding to a random (OS choice) port is not user friendly as it makes the browsers history function useless.

**Comment by sevagh** [comment]
@Scheirle Only as a second choice if 8000 is taken

**Comment by justinmayer** [comment]
I imagine the current behavior is probably best from a "principle of least astonishment" perspective. My concern is that users may not realize an alternate port has been allocated and then be confused when the browser does not show what the user expects.

**Comment by moorepants** [comment]
One reason I was expecting different behavior than found was because the IPython Notebook allows you to open as many servers as you'd like, staring count from port 8000. First terminal:

```
moorepants@garuda:~$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
[I 15:09:54.048 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 15:09:54.147 NotebookApp] Serving notebooks from local directory: /home/moorepants
[I 15:09:54.147 NotebookApp] 0 active kernels 
[I 15:09:54.147 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 15:09:54.147 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

Second terminal:

```
moorepants@garuda:~$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
[I 15:10:05.857 NotebookApp] The port 8888 is already in use, trying another random port.
[I 15:10:05.863 NotebookApp] Serving notebooks from local directory: /home/moorepants
[I 15:10:05.863 NotebookApp] 0 active kernels 
[I 15:10:05.863 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
[I 15:10:05.863 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

I've seen this on other packages that launch servers too and guess I thought it was standard practice. It surprised me when Pelican threw an error instead of picking a different port.

**Comment by lincolnfrias** [comment]
Indeed @moorepants, I just landed on this page trying to solve this: 

```
ERROR:root:Could not listen on port 8000, server .
Makefile:61: recipe for target 'serve' failed
make: *** [serve] Error 1

```
What should I do?

**Comment by justinmayer** [comment]
Closing this issue since it has been open for a year without anyone stepping forward to work on it. If someone would like to implement this feature, please comment here and I will re-open the issue.
