### ISSUE TITLE
AttributeError: SimplerXMLGenerator instance has no attribute '_write'

### ISSUE THREAD

**Issue by jie** [getpelican/pelican#1977]
when using make html command

**Comment by jie** [comment]
CRITICAL: AttributeError: SimplerXMLGenerator instance has no attribute '_write'
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/pelican/__init__.py", line 478, in main
    pelican.run()
  File "/usr/local/lib/python2.7/site-packages/pelican/__init__.py", line 183, in run
    p.generate_output(writer)
  File "/usr/local/lib/python2.7/site-packages/pelican/generators.py", line 586, in generate_output
    self.generate_feeds(writer)
  File "/usr/local/lib/python2.7/site-packages/pelican/generators.py", line 318, in generate_feeds
    % auth.slug)
  File "/usr/local/lib/python2.7/site-packages/pelican/writers.py", line 119, in write_feed
    feed.write(fp, 'utf-8')
  File "/usr/local/lib/python2.7/site-packages/feedgenerator/django/utils/feedgenerator.py", line 307, in write
    handler.startElement('feed', self.root_attributes())
  File "/usr/local/lib/python2.7/site-packages/feedgenerator/django/utils/xmlutils.py", line 19, in startElement
    self._write('<' + name)
AttributeError: SimplerXMLGenerator instance has no attribute '_write'

**Comment by ingwinlu** [comment]
please read https://github.com/getpelican/pelican/blob/master/CONTRIBUTING.rst and extend your bug report

**Comment by leotrs** [comment]
@jie please extend or close. I find no mention of a `SimplerXMLGenerator` in the pelican codebase. Does this come from a plugin instead?

**Comment by jie** [comment]
in pelican/writers.py

find 'from feedgenerator import Atom1Feed, Rss201rev2Feed'

Maybe 'SimplerXMLGenerator' used by this package

**Comment by leotrs** [comment]
It would seem it does. Can you please expand a bit more? What were you doing? What's the setup? I can run `make html` with no problems, but I don't generate feeds. Are you doing something in particular with feeds? Can you try with a different theme or with different plugins active? Thanks.

**Comment by avaris** [comment]
@jie `SimpleXMLGenerator` supposed to be from the built-in `xml` module. Do you have any third-party xml modules that might shadow this? IIRC, `PyXML` did this. Either remove that or run your `pelican` setup from a virtualenv.

**Comment by jie** [comment]
@avaris
thanks
