### ISSUE TITLE
exception raised in pelican-quickstart v3.7.0 w/Python 2: *** AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by cs01** [getpelican/pelican#2084]
Python 2 does not handle missing locales as nicely as Python 3, and the following error is raised on a vanilla install of pelican:

```
>> pelican-quickstart
Traceback (most recent call last):
  File ".../.virtualenv/bin/pelican-quickstart", line 7, in <module>
    from pelican.tools.pelican_quickstart import main
  File ".../.virtualenv/local/lib/python2.7/site-packages/pelican/tools/pelican_quickstart.py", line 52, in <module>
    'lang': locale.getlocale()[0].split('_')[0],
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by cs01** [comment]
This is a duplicate of #2043. The pypi package has not yet been fixed, but the sourcecode has.

**Comment by justinmayer** [comment]
Pelican 3.7.1 has been released, containing a fix for this problem. Apologies for any frustration caused!
