### ISSUE TITLE
pelican-quickstart returns syntax error 

### ISSUE THREAD

**Issue by afadallah** [getpelican/pelican#2110]
Hi,

Installed pelican 3.7.1 , on CentOS 6.5. However, pelican-quickstart fails to launch. Similarly, importing the package in python returns:

>>> import pelican
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pelican/__init__.py", line 424
    modified = {k: next(v) for k, v in watchers.items()}
                             ^
SyntaxError: invalid syntax

Regards,
Ahmed

**Comment by ingwinlu** [comment]
we don't support python 2.6

**Comment by afadallah** [comment]
Tried installing an earlier release, pelican 3.6.3. Got a similar error:

Traceback (most recent call last):
  File "/usr/bin/pelican-quickstart", line 9, in <module>
    load_entry_point('pelican==3.6.3', 'console_scripts', 'pelican-quickstart')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/pelican-3.6.3-py2.6.egg/pelican/__init__.py", line 417
    modified = {k: next(v) for k, v in watchers.items()}
                             ^
SyntaxError: invalid syntax

I didn't experience this problem when I installed pelican on Ubuntu in the past. I suspect it has to do with the fact that my CentOS distribution runs on python 2.6...

**Comment by afadallah** [comment]
@ingwinlu, yes. I'll set up a virtualenv. thank you.

**Comment by justinmayer** [comment]
Your version of Python (2.6) is too old. As noted in our docs, we support Pelican on Python 2.7+.
