### ISSUE TITLE
Pelican ModuleNotFoundError: No module named 'j'

### ISSUE THREAD

**Issue by Flobin** [getpelican/pelican#2206]
I’m using Pelican to set up a static site. When I try to generate it, I get the following error: `CRITICAL: ModuleNotFoundError: No module named 'j'`

The command I used is `pelican content -s pelicanconf.py`.

This is my [pelicanconf.py](https://gist.github.com/Flobin/306c8833fdf2e89ccce3bc7d9d48c42b#file-pelicanconf-py). This is my [requirements.txt](https://gist.github.com/Flobin/306c8833fdf2e89ccce3bc7d9d48c42b#file-requirements-txt). I'm using Python 3.6 in a virtual environment.

What is this module named ‘j’?

**Comment by jorgesumle** [comment]
Does this happen without plugins or executing `pelican -s pelicanconf.py content`?

If you still experience this problem, execute pelican with the debug flag (pelican --debug -s pelicanconf.py content) and paste its output here.

**Comment by Flobin** [comment]
@jorgesumle thanks for the quick response!

This is what I get with the debug flag:

    DEBUG: Pelican version: 3.7.1
    DEBUG: Python version: 3.6.0
    WARNING: Removed extraneous trailing slash from SITEURL.
    DEBUG: Adding current directory to system path
    DEBUG: Temporarily adding PLUGIN_PATHS to system path
    DEBUG: Loading plugin `i18n_subsites`
    DEBUG: Registering plugin `i18n_subsites`
    DEBUG: Loading plugin `neighbors`
    DEBUG: Registering plugin `neighbors`
    DEBUG: Loading plugin `sitemap`
    DEBUG: Registering plugin `sitemap`
    DEBUG: Restoring system path
    DEBUG: Found generator: <class 'sitemap.sitemap.SitemapGenerator'>
    CRITICAL: ModuleNotFoundError: No module named 'j'
    Traceback (most recent call last):
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/bin/pelican", line 11, in <module>
        sys.exit(main())
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 487, in main
        pelican.run()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 160, in run
        ) for cls in self.get_generator_classes()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 160, in <listcomp>
        ) for cls in self.get_generator_classes()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/generators.py", line 277, in __init__
        super(ArticlesGenerator, self).__init__(*args, **kwargs)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/generators.py", line 217, in __init__
        **kwargs)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/generators.py", line 69, in __init__
        **self.settings['JINJA_ENVIRONMENT']
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/jinja2/environment.py", line 333, in __init__
        self.extensions = load_extensions(self, extensions)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/jinja2/environment.py", line 85, in load_extensions
        extension = import_string(extension)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/jinja2/utils.py", line 142, in import_string
        return __import__(import_name)
    ModuleNotFoundError: No module named 'j'

**Comment by avaris** [comment]
Yes, `extensions` should be a list:
```python
JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}
```

**Comment by Flobin** [comment]
@avaris thanks!

It seems like the i18n plugin is still looking for `JINJA_EXTENSIONS`, or am I reading this stack trace wrong?

    CRITICAL: KeyError: 'JINJA_EXTENSIONS'
    Traceback (most recent call last):
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/bin/pelican", line 11, in <module>
        sys.exit(main())
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 487, in main
        pelican.run()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 175, in run
        writer = self.get_writer()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 242, in get_writer
        writers = [w for (_, w) in signals.get_writer.send(self)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/blinker/base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
        for receiver in self.receivers_for(sender)]
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/pelican-plugins/i18n_subsites/i18n_subsites.py", line 418, in create_next_subsite
        new_pelican_obj.run()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 175, in run
        writer = self.get_writer()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/pelican/__init__.py", line 242, in get_writer
        writers = [w for (_, w) in signals.get_writer.send(self)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/blinker/base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/venv/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
        for receiver in self.receivers_for(sender)]
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/pelican-plugins/i18n_subsites/i18n_subsites.py", line 405, in create_next_subsite
        update_generators()
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/pelican-plugins/i18n_subsites/i18n_subsites.py", line 374, in update_generators
        install_templates_translations(generator)
      File "/Users/robin/work/2017-08-15_robin.berghuijs.design/pelican-plugins/i18n_subsites/i18n_subsites.py", line 273, in install_templates_translations
        if 'jinja2.ext.i18n' in generator.settings['JINJA_EXTENSIONS']:
    KeyError: 'JINJA_EXTENSIONS'

**Comment by avaris** [comment]
@Flobin It looks like you have an older version of the plugin (one that's incompatible with pelican 3.7). Try updating plugins to the latest from the master.

**Comment by Flobin** [comment]
@avaris thanks so much, this solved my issue!

**Comment by acz13** [comment]
Needs to be closed

**Comment by justinmayer** [comment]
Thanks to @avaris for the assistance and to @acz13 for the nudge.

@Flobin: Please feel free to close issues once your problem has been resolved. Also, in the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
