### ISSUE TITLE
"make github" is failing in newer git versions

### ISSUE THREAD

**Issue by Sirtea** [getpelican/pelican#2262]
Hi,

**This is an upstream error, so please forward it and adapt pelican as needed**

I have my pelican instance on a docker container based on alpine linux, that launched version 3.7 lately.
Today, when tried to publish with the new alpine 3.7 container, it fails:

```
/pelican/sites/linuxsysadmin $ make github
pelican /pelican/sites/linuxsysadmin/content -o /pelican/sites/linuxsysadmin/output -s /pelican/sites/linuxsysadmin/publishconf.py
Done: Processed 114 articles, 0 drafts, 1 page and 1 hidden page in 5.15 seconds.
ghp-import -m "Generate Pelican site" -b gh-pages /pelican/sites/linuxsysadmin/output
git: 'fast-import' is not a git command. See 'git --help'.

The most similar command is
        fast-export
Traceback (most recent call last):
  File "/usr/bin/ghp-import", line 11, in <module>
    load_entry_point('ghp-import==0.5.5', 'console_scripts', 'ghp-import')()
  File "/usr/lib/python2.7/site-packages/ghp_import.py", line 238, in main
    run_import(git, args[0], opts)
  File "/usr/lib/python2.7/site-packages/ghp_import.py", line 173, in run_import
    start_commit(pipe, git, opts.branch, opts.mesg)
  File "/usr/lib/python2.7/site-packages/ghp_import.py", line 127, in start_commit
    write(pipe, enc('commit refs/heads/%s\n' % branch))
  File "/usr/lib/python2.7/site-packages/ghp_import.py", line 47, in write
    pipe.stdin.write(data)
IOError: [Errno 32] Broken pipe
make: *** [Makefile:122: github] Error 1
/pelican/sites/linuxsysadmin $
```

This error is because "ghp-import" fails when executing "git fast-import", which seems missing on new release of git, Attached the evidence of two different versions: a git 2.13.5 that recognizes the command (although I use it bad willingly) and a git 2.15.0 that does not.

```
/ # grep PRETTY /etc/os-release
PRETTY_NAME="Alpine Linux v3.6"
/ # git --version
git version 2.13.5
/ # git fast-import
fatal: Not a git repository (or any of the parent directories): .git
/ #
```

```
/ # grep PRETTY /etc/os-release
PRETTY_NAME="Alpine Linux v3.7"
/ # git --version
git version 2.15.0
/ # git fast-import
git: 'fast-import' is not a git command. See 'git --help'.

The most similar command is
        fast-export
/ #
```

**Comment by Sirtea** [comment]
Similar git version found on Debian testing, and works, so this can be closed as is a bug on alpine linux:

```
root@33f55ab8c8d0:/# grep PRETTY /etc/os-release
PRETTY_NAME="Debian GNU/Linux buster/sid"
root@33f55ab8c8d0:/# git --version
git version 2.15.1
root@33f55ab8c8d0:/# git fast-import
fatal: Not a git repository (or any of the parent directories): .git
root@33f55ab8c8d0:/#
```

**Comment by ganwell** [comment]
In alpine-linux this is resolved by calling:

```apk add git-fast-import```

**Comment by Sirtea** [comment]
Yes

Alpine Linux mantainers told me that the command "git fast-import" was stripped from the package "git" to package "git-fast-import" to reduce git size, while keeping the general use case for most users.

This has been tested and works.
