### ISSUE TITLE
macosx python 3 and 2.7: ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by manelclos** [getpelican/pelican#2297]
Hi!
Tried both Python 3 and Python 2 with same result:

```
pelican-quickstart 
Traceback (most recent call last):
  File "/Users/manel/devel/opensource/pygrn/scms/venv/bin/pelican-quickstart", line 7, in <module>
    from pelican.tools.pelican_quickstart import main
  File "/Users/manel/devel/opensource/pygrn/scms/venv/lib/python2.7/site-packages/pelican/tools/pelican_quickstart.py", line 25, in <module>
    _DEFAULT_LANGUAGE = locale.getlocale()[0]
  File "/Users/manel/devel/opensource/pygrn/scms/venv/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/Users/manel/devel/opensource/pygrn/scms/venv/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by justinmayer** [comment]
A good way to troubleshoot errors is to try using the error as a search term across the Internet:

http://www.lmgtfy.com/?q=ValueError%3A+unknown+locale%3A+UTF-8

By doing that, you'll almost always find someone else who has run into the same problem, along with a solution. If you need further assistance, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!

**Comment by manelclos** [comment]
@justinmayer thanks! Sure thing, that is what I always do. I thought I'd report it as a bug since it can be easily intercepted, and if not fix it, point the user to the solution.

**Comment by justinmayer** [comment]
I agree that would be helpful. Is that something you'd be willing to help improve? If so, I'd be happy to re-open the issue.

**Comment by manelclos** [comment]
What about this, it works for me (same as you do for _DEFAULT_TIMEZONE):

```
locale.setlocale(locale.LC_ALL, '')
try:
    _DEFAULT_LANGUAGE = locale.getlocale()[0]
except Exception:
    _DEFAULT_LANGUAGE = None
if _DEFAULT_LANGUAGE is None:
    _DEFAULT_LANGUAGE = 'English'
else:
    _DEFAULT_LANGUAGE = _DEFAULT_LANGUAGE.split('_')[0]
```

**Comment by justinmayer** [comment]
Let's ask our resident locale expert, @avaris... What do you think?

**Comment by avaris** [comment]
Effectively this is an issue with [Python and OSX](https://bugs.python.org/issue18378). But it's fine to circumvent it, I guess. It doesn't seem to be going away soon. 

As for the patch, just catch the exact exception please (`ValueError`). `except Exception` is far too broad. Plus, maybe a comment why that's needed.

**Comment by manelclos** [comment]
Done. I used ValueError initially, but then I thought that any exception while autodetecting the language is not as important as keeping the quickstart process going. The PR only catches ValueError though.
