### ISSUE TITLE
pelican-quickstart UnicodeDecodeError

### ISSUE THREAD

**Issue by giuntim** [getpelican/pelican#2345]
```
$ pelican-quickstart

Welcome to pelican-quickstart v3.7.1.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.

    
> Where do you want to create your new web site? [.] 
> What will be the title of this web site? Pelican test
> Who will be the author of this web site? Maurizio
> What will be the default language of this web site? [it] 
> Do you want to specify a URL prefix? e.g., http://example.com   (Y/n) n
> Do you want to enable article pagination? (Y/n) 
> How many articles per page do you want? [10] 
> What is your time zone? [Europe/Paris] 
> Do you want to generate a Fabfile/Makefile to automate generation and publishing? (Y/n) y
> Do you want an auto-reload & simpleHTTP script to assist with theme and site development? (Y/n) n
> Do you want to upload your website using FTP? (y/N) 
> Do you want to upload your website using SSH? (y/N) 
> Do you want to upload your website using Dropbox? (y/N) 
> Do you want to upload your website using S3? (y/N) 
> Do you want to upload your website using Rackspace Cloud Files? (y/N) 
> Do you want to upload your website using GitHub Pages? (y/N) 
Traceback (most recent call last):
  File "/usr/bin/pelican-quickstart", line 11, in <module>
    load_entry_point('pelican==3.7.1', 'console_scripts', 'pelican-quickstart')()
  File "/home/maurizio/.local/lib/python2.7/site-packages/pelican/tools/pelican_quickstart.py", line 329, in main
    print('Error: {0}'.format(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 18: ordinal not in range(128)
```

**Comment by justinmayer** [comment]
Hi Maurizio. If you need additional assistance, please reach out as via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
