### ISSUE TITLE
Pelican import fails with errors

### ISSUE THREAD

**Issue by bmansheim** [getpelican/pelican#2385]
I ran an  export of a section of my WordPress site through the importer and got:

Traceback (most recent call last):
  File "/usr/local/bin/pelican-import", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_import.py", line 896, in main
    attachments=attachments or None)
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_import.py", line 684, in fields2pelican
    kind, in_markup) in fields:
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_import.py", line 145, in wp2fields
    items = get_items(xml)
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_import.py", line 131, in get_items
    items = soup.rss.channel.findAll('item')
AttributeError: 'NoneType' object has no attribute 'channel'

Is it a problem in my export?

**Comment by justinmayer** [comment]
I'm not sure. Possibly addressed by #2366. Once that's merged, would you be willing to try on master and see if that resolves your problem?
