### ISSUE TITLE
pagination undefined articles_page

### ISSUE THREAD

**Issue by mariuspana** [getpelican/pelican#2420]
Hi,

Ive looked through other issues (most notably #2280) that had the same or similar errors as mine without much headway. I've also thoroughly looked through the documentation playing with different configuration options such as DIRECT_TEMPLATES, PAGINATED_DIRECT_TEMPLATES and TEMPLATE_PAGES.

My entire pelican site is available [here](https://code.spearhead.cloud/Spearhead/www.spearhead.systems) and I cannot for the life of me get a custom blog template to paginate the articles list. Every option/configuration I've tried still throws the articles_page undefined error.

Any help would be much appreciated.

Thanks,
Marius

**Comment by avaris** [comment]
Your link gives me 404.

**Comment by mariuspana** [comment]
my bad, the repo was not public

**Comment by mariuspana** [comment]
Thanks for the feedback. Unfortunately, with the recommended configuration I am in the same situation: articles_page is not defined. I also had to remove the page.title variable from the blog-index template (no biggie since it is only being used for this specific page) but once I activate the paging code (uncomment it) it still throws the following:

```
CRITICAL: UndefinedError: 'articles_page' is undefined
Traceback (most recent call last):
  File "/Users/mpana/Development/www.spearhead.systems/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/pelican/__init__.py", line 465, in main
    pelican.run()
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/pelican/generators.py", line 675, in generate_output
    override_output=hasattr(page, 'override_save_as'))
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/pelican/writers.py", line 230, in write_file
    override_output)
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/pelican/writers.py", line 171, in _write_file
    output = template.render(localcontext)
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/mpana/Development/www.spearhead.systems/www/themes/spearhead/templates/blog-index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/mpana/Development/www.spearhead.systems/www/themes/spearhead/templates/base.html", line 136, in top-level template code
    {% block content %}
  File "/Users/mpana/Development/www.spearhead.systems/www/themes/spearhead/templates/blog-index.html", line 39, in block "content"
    {% include 'pagination.html' %}
  File "/Users/mpana/Development/www.spearhead.systems/www/themes/spearhead/templates/pagination.html", line 3, in top-level template code
    {% if articles_page.has_previous() %}
  File "/Users/mpana/Development/www.spearhead.systems/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'articles_page' is undefined
```

**Comment by mariuspana** [comment]
Awesome @avaris. Thank you very much for your help! 
I knew it should be possible but I just could not get my head around using templates and these variables. The realisation that of how we can use template name variables with *_save_as is awesome.

**Comment by dvphucsgt** [comment]
@avaris
Thank you 🙇
