### ISSUE TITLE
Feed import failed 

### ISSUE THREAD

**Issue by reikkaps** [getpelican/pelican#2498]
i tried to import some rss feeds, but the command always failed with the following error:
```
pelican-import -o import/ --feed https://www.heise.de/rss/heise-atom.xml 
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
Traceback (most recent call last):
```
```python
  File "/home/reik/Dokumente/Projekte/glocksee.org/venv/bin/pelican-import", line 11, in <module>
    sys.exit(main())
  File "/home/reik/Dokumente/Projekte/glocksee.org/venv/lib/python3.6/site-packages/pelican/tools/pelican_import.py", line 1019, in main
    attachments=attachments or None)
  File "/home/reik/Dokumente/Projekte/glocksee.org/venv/lib/python3.6/site-packages/pelican/tools/pelican_import.py", line 780, in fields2pelican
    kind, in_markup) in fields:
  File "/home/reik/Dokumente/Projekte/glocksee.org/venv/lib/python3.6/site-packages/pelican/tools/pelican_import.py", line 567, in feed2fields
    if hasattr(entry, 'updated_parsed') else None)
AttributeError: 'time.struct_time' object has no attribute 'strftime'
```

**Comment by avaris** [comment]
Tracking this back to the cause gives #2395, particularly [this change](https://github.com/getpelican/pelican/pull/2395/files#diff-c13027ccd29dd35523f0d18b467d8b6cL502). `feedparser` returns time tuples and those don't have `strftime`. To be sure before reverting that, @oulenz do you remember why did you change that?

**Comment by oulenz** [comment]
Unfortunately, I don't remember why I added that, and I don't see any connection with the blogger importer. So I think we can just revert.
