### ISSUE TITLE
Pelican crashes when generating articles

### ISSUE THREAD

**Issue by yifeikong** [getpelican/pelican#2541]
```
CRITICAL: TypeError: can't compare offset-naive and offset-aware datetimes
Traceback (most recent call last):
  File "/home/kongyifei/repos/yifeikong.github.io/.venv/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/kongyifei/repos/yifeikong.github.io/.venv/lib/python3.6/site-packages/pelican/__init__.py", line 623, in main
    pelican.run()
  File "/home/kongyifei/repos/yifeikong.github.io/.venv/lib/python3.6/site-packages/pelican/__init__.py", line 178, in run
    p.generate_context()
  File "/home/kongyifei/repos/yifeikong.github.io/.venv/lib/python3.6/site-packages/pelican/generators.py", line 653, in generate_context
    self.drafts, self.drafts_translations = _process(all_drafts)
  File "/home/kongyifei/repos/yifeikong.github.io/.venv/lib/python3.6/site-packages/pelican/generators.py", line 649, in _process
    origs = order_content(origs, self.settings['ARTICLE_ORDER_BY'])
  File "/home/kongyifei/repos/yifeikong.github.io/.venv/lib/python3.6/site-packages/pelican/utils.py", line 764, in order_content
    reverse=order_reversed)
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by yifeikong** [comment]
The error happens when I have `Date` and `Modified` in some articles and not in others.

**Comment by avaris** [comment]
Probably related to #2524

**Comment by justinmayer** [comment]
Closing in favor of aforementioned issue.
