### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2597]
```
CRITICAL: RuntimeError: generator raised StopIteration
make: *** [Makefile:87: publish] Error 1
```

Now, [my GitLab CI tests fail](https://gitlab.com/Freak-Spot/Freak-Spot/-/jobs/258097617). It looks like [PEP 479](https://www.python.org/dev/peps/pep-0479/) introduced in Python 3.7 is to blame. Locally I don't get any error. Maybe this happens only with computers with less resources, according to PEP 479:

> This PEP proposes a change to generators: when StopIteration is raised inside a generator, it is replaced it with RuntimeError. (More precisely, this happens when the exception is about to bubble out of the generator's stack frame.)

**Comment by justinmayer** [comment]
Sorry to hear that, @jorgesumle. Is this something you would be willing to help out with and work on fixing?

**Comment by avaris** [comment]
Can we see `--debug` output?

FWIW, nothing in `pelican` does `raise StopIteration`. I'm inclined to blame plugins/themes :).

**Comment by jorgesumle** [comment]
It is raised by the neighbors plugin:

```
Traceback (most recent call last):
  File "/builds/Freak-Spot/Freak-Spot/plugins/neighbors/neighbors.py", line 14, in iter3
    cur = next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 631, in main
    pelican.run()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 194, in run
    writer = self.get_writer()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 268, in get_writer
    writers = [w for (_, w) in signals.get_writer.send(self)
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/builds/Freak-Spot/Freak-Spot/plugins/i18n_subsites/i18n_subsites.py", line 436, in create_next_subsite
    new_pelican_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 186, in run
    p.generate_context()
  File "/usr/local/lib/python3.7/dist-packages/pelican/generators.py", line 685, in generate_context
    signals.article_generator_finalized.send(self)
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.7/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/builds/Freak-Spot/Freak-Spot/plugins/neighbors/neighbors.py", line 42, in neighbors
    set_neighbors(generator.articles, 'next_article', 'prev_article')
  File "/builds/Freak-Spot/Freak-Spot/plugins/neighbors/neighbors.py", line 29, in set_neighbors
    for nxt, cur, prv in iter3(articles):
RuntimeError: generator raised StopIteration
```

**Comment by wine3603** [comment]
I solve this bug by [this](https://github.com/getpelican/pelican-plugins/pull/1238)
