### ISSUE TITLE
Rewrite Error

### ISSUE THREAD

**Issue by joncyr** [getpelican/pelican#2614]
Hi,

Been messing with this for a few days, so I hope I get the problem across.

I'm using Pelican as a reportwriter... I generate custom markdown files, and Pelican assembles them into a website.  I seem to have run up on a capacity limit of sorts.

I have two large sections of the report broken into 10 files each totalling 6-7 Mbytes.  One set is called audit and the other called reference.  Anyway when I build the website with just audit or just reference, it takes 3min or so, but it builds correctly.  

When I try to build using both audit and reference I get the following error

```
CRITICAL: RuntimeError: File /pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/output/audit-report-for-ruleset-1-pci-dss-v3-control-baseline-for-red-hat-enterprise-linux-7.html is to be overwritten
Traceback (most recent call last):
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/__init__.py", line 631, in main
    pelican.run()
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/__init__.py", line 198, in run
    p.generate_output(writer)
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/generators.py", line 689, in generate_output
    self.generate_pages(writer)
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/generators.py", line 598, in generate_pages
    self.generate_articles(write)
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/generators.py", line 470, in generate_articles
    url=article.url, blog=True)
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/writers.py", line 272, in write_file
    override_output)
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/writers.py", line 212, in _write_file
    with self._open_w(path, 'utf-8', override=override) as f:
  File "/pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/reportbuilder-py36/lib64/python3.6/site-packages/pelican/writers.py", line 112, in _open_w
    raise RuntimeError('File %s is to be overwritten' % filename)
RuntimeError: File /pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/output/audit-report-for-ruleset-1-pci-dss-v3-control-baseline-for-red-hat-enterprise-linux-7.html is to be overwritten
(reportbuilder-py36) [root@ip-172-31-47-141 pelicanproject-reportbuilder]# ^C
```

So, I build successfully using most of the files, but when I add the last set, it fails.  And it doesnt matter which files I add.   It seems to be capacity driven.

names changed to hide my client's name.

Attached
- Successful run --debug data
- Unsuccessful run (adding reference set)  -debug data
[sizes-environment.txt](https://github.com/getpelican/pelican/files/3560643/sizes-environment.txt)
[successful.txt](https://github.com/getpelican/pelican/files/3560644/successful.txt)
[unsuccessful.txt](https://github.com/getpelican/pelican/files/3560645/unsuccessful.txt)

- File Sizes, Pip List, and Pelican config file

Any ideas would be appreciated.

-Jon

**Comment by avaris** [comment]
It's not capacity. You have multiple files with same slug with same language, i.e.:
```
WARNING: There are 2 items "with slug "audit-report-for-ruleset-1-pci-dss-v3-control-baseline-for-red-hat-enterprise-linux-7"" with lang en: 
  | /pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/content/audit-report-for-ruleset-1-pci-dss-v3-control-baseline-for-red-hat-enterprise-linux-7.md
  | /pelicanproject-workspace/dev-rhel75-pelicanproject-data/pelicanproject-data/pelicanproject-reportbuilder/content/reference-manual-for-ruleset-1-pci-dss-v3-control-baseline-for-red-hat-enterprise-linux-7.md
```

and given that your `ARTICLE_SAVE_AS` is default (`{slug}.html`), they will be written at the same file, thus overwriting each other. When something like that happens (i.e. some content would write over another written content), `pelican` considers it as an error and stops.

You need to adjust your slugs or `ARTICLE_SAVE_AS` (+ `ARTICLE_URL`) so that each content will go to a unique location.

**Comment by justinmayer** [comment]
@joncyr: Hopefully the guidance provided by @avaris has been useful. Feel free to comment here if you need further assistance.
