### ISSUE TITLE
pelican  4.2.0 cant cache lambda in pelicancof.py

### ISSUE THREAD

**Issue by est** [getpelican/pelican#2677]
```
CATEGORY_REGEX_SUBSTITUTIONS = [
    (r'^(myca1|myca2)?(.*)$', lambda m: m.group(1) or 'archive'),
]
```

So I had lots of imported blog and I want to only handle 2 categories like `myca1` and `myca2` I use this trick to convert rest of category to `archive`.

However this seems to conflict with `LOAD_CONTENT_CACHE = True`

Can we *not* cache the config file?

**Comment by avaris** [comment]
We *don't* cache the config file. What is the exact error?

**Comment by est** [comment]
It says 

    PicklingError: Can't pickle <function <lambda> at 0x10fe82378>: attribute lookup <lambda> on pelicanconf failed

**Comment by avaris** [comment]
Can you run `pelican` with `--debug` flag to get a full error?

**Comment by est** [comment]
Hi,

This is the result

  $ ~/miniconda3/bin/python -i -m pelican --debug
  DEBUG: Pelican version: 4.2.0
  DEBUG: Python version: 3.7.3
  WARNING: Feeds generated without SITEURL set properly may not be valid
  DEBUG: Adding current directory to system path
  DEBUG: Temporarily adding PLUGIN_PATHS to system path
  DEBUG: Loading plugin `fix_rss_link`
  DEBUG: Registering plugin `fix_rss_link`
  DEBUG: Loading plugin `sitemap`
  DEBUG: Registering plugin `sitemap`
  DEBUG: Restoring system path
  DEBUG: Found generator: <class 'sitemap.SitemapGenerator'>
  CRITICAL: EOFError: Ran out of input
  Traceback (most recent call last):
    File "/Users/me/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/me/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/__main__.py", line 10, in <module>
      main()
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/__init__.py", line 570, in main
      pelican.run()
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/__init__.py", line 114, in run
      ) for cls in self.get_generator_classes()
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/__init__.py", line 114, in <listcomp>
      ) for cls in self.get_generator_classes()
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/generators.py", line 297, in __init__
      super(ArticlesGenerator, self).__init__(*args, **kwargs)
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/generators.py", line 237, in __init__
      **kwargs)
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/generators.py", line 51, in __init__
      self.readers = Readers(self.settings, readers_cache_name)
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/readers.py", line 547, in __init__
      caching_policy, load_policy,
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/cache.py", line 87, in __init__
      load_policy)
    File "/Users/me/miniconda3/lib/python3.7/site-packages/pelican/cache.py", line 37, in __init__
      self._cache = pickle.load(fhandle)
  EOFError: Ran out of input
  >>>

**Comment by est** [comment]
Upon further investigating it's possibly my own problem related to  https://github.com/getpelican/pelican/pull/2548

Sorry for the confusion. I added too many hacks to my config.
