### ISSUE TITLE
Importing wordpress export xml file gets "AttributeError" error

### ISSUE THREAD

**Issue by pyotr777** [getpelican/pelican#2680]
Exported published posts from WordPress 5.2.5 into WordPress.2020-01-06.xml file.

```
pelican-import -m markdown --wpfile WordPress.2020-01-06.xml -o ./output/`

WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
...
Traceback (most recent call last):
  File "/usr/local/bin/pelican-import", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pelican/tools/pelican_import.py", line 1026, in main
    attachments=attachments or None)
  File "/usr/local/lib/python3.7/site-packages/pelican/tools/pelican_import.py", line 787, in fields2pelican
    kind, in_markup) in fields:
  File "/usr/local/lib/python3.7/site-packages/pelican/tools/pelican_import.py", line 149, in wp2fields
    if item.find('status').string in ["publish", "draft"]:
AttributeError: 'NoneType' object has no attribute 'string'
```

Pelican version 4.2.0.

Similar issue: #2144.

**Comment by pyotr777** [comment]
Found invalid characters in the XML file with xmllint.
