### ISSUE TITLE
Missing standard Pelican variables during Jinja2 templating?

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2697]
I'm trying to figure out why the Current Pelican Standard Variables as listed in the [current Pelican document](https://docs.getpelican.com/en/stable/themes.html)  are NOT available from within Jinja2 scope. .

When drafting a custom cover/landing templating page, I've created a bare `cover.html` in my theme's template/my-theme/templates/ directory.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>{% output_file %}</title>  <!--  <-- our focus -->
  </head>
  <body>
Title is {% title %}
  </body>
</html>
```
Focus on the placement of Jinja2 `output_file` variable inside the Jinja-notated `{% ... %}` block  above.  This `output_file` should be made available as described in this [current Pelican document](https://docs.getpelican.com/en/stable/themes.html).

Then created a Markdown `cover.md` in the Pelican's `content/pages/` subdirectory as shown below:

```md
Title: Cover Page
Template: cover
Date: 2020-02-19 10:28
Summary: What would be a cover page if we know what Pelican passes for a variable for Jinja2 to  use.

Cover Page goes here with the string value of output_file variable as its title.
```
`Title` is defined in above Markdown document.  `cover` is this Pelican template to use.

Running pelican takes this `cover.md` and applies the `cover.html` template:

```bash
make html
pelican -o ./output -s pelicanconf.py ./content
```
then errors out at:

```
CRITICAL: TemplateSyntaxError: Encountered unknown tag 'output_file'.
make: *** [Makefile:47: html] Error 1
```

I've tried the following OTHER standard Pelican variables to no avail:

* `pages`
* `articles`
* `tags`

Tried some weird ones:

* `cover`

All produced the same error message.

Debug added for additional output:

```bash
DEBUG=1 make html
pelican -o ./output -s ./pelicanconf.py  -D content
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.7.3
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Registering plugin `collate_content`
DEBUG: Registering plugin `sitemap`
DEBUG: Registering plugin `dateish`
DEBUG: Registering plugin `tag_cloud`
DEBUG: Registering plugin `alias`
DEBUG: Registering plugin `htmlsanity`
DEBUG: Registering plugin `just_table`
DEBUG: Registering plugin `code_include`
DEBUG: Restoring system path
DEBUG: Found generator: <class 'sitemap.sitemap.SitemapGenerator'>
DEBUG: Found generator: <class 'alias.AliasGenerator'>
DEBUG: Template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/authors.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/period_archives.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', '!theme/archives.html', '!theme/article.html', '!theme/article_badges.html', '!theme/article_footer.html', '!theme/article_header.html', '!theme/author.html', '!theme/base.html', '!theme/base_blog.html', '!theme/base_blog_section.html', '!theme/category.html', '!theme/cover.html', '!theme/index.html', '!theme/page.html', '!theme/pagination.html', '!theme/passthrough.html', '!theme/tag.html', 'archives.html', 'article.html', 'article_badges.html', 'article_footer.html', 'article_header.html', 'author.html', 'authors.html', 'base.html', 'base_blog.html', 'base_blog_section.html', 'categories.html', 'category.html', 'cover.html', 'index.html', 'page.html', 'pagination.html', 'passthrough.html', 'period_archives.html', 'tag.html', 'tags.html', 'translations.html']
DEBUG: Read file articles/bind9-keys.md -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
DEBUG: Successfuly imported extension module "markdown.extensions.smarty".
DEBUG: Successfully loaded extension "markdown.extensions.smarty.SmartyExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.extra".
DEBUG: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
DEBUG: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
DEBUG: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
DEBUG: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
DEBUG: Successfully loaded extension "markdown.extensions.tables.TableExtension".
DEBUG: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
DEBUG: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.footnotes".
DEBUG: Successfuly imported extension module "markdown.extensions.meta".
DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.toc".
DEBUG: Successfully loaded extension "markdown.extensions.toc.TocExtension".
DEBUG: Successfuly imported extension module "markdown.extensions.codehilite".
DEBUG: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
DEBUG: Read file pages/about.md -> Page
DEBUG: Signal page_generator_preread.send(PagesGenerator)
DEBUG: Signal page_generator_context.send(PagesGenerator, <metadata>)
DEBUG: Read file pages/uses.md -> Page
DEBUG: Read file pages/sitemap.md -> Page
DEBUG: Read file pages/404.md -> Page
DEBUG: Read file pages/landing.md -> Page
DEBUG: Read file pages/privacy.md -> Page
DEBUG: Read file pages/cover.md -> Page
DEBUG: Read file extra/keybase.txt -> Static
DEBUG: Signal static_generator_preread.send(StaticGenerator)
DEBUG: Signal static_generator_context.send(StaticGenerator, <metadata>)
DEBUG: Read file extra/ss-css.css -> Static
DEBUG: Read file images/pelican-2-git-repos.svg -> Static
DEBUG: Read file extra/robots.txt -> Static
-> Writing /home/XXXXX/output/atom.xml
-> Writing /home/XXXXX/output/blog/pages/uses.html
-> Writing /home/XXXXX/output/blog/pages/about.html
-> Writing /home/XXXXX/output/blog/pages/site-map.html

CRITICAL: TemplateSyntaxError: Encountered unknown tag 'output_file'.
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 570, in main
    pelican.run()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 137, in run
    p.generate_output(writer)
  File "/usr/local/lib/python3.7/dist-packages/pelican/generators.py", line 774, in generate_output
    page.save_as, self.get_template(page.template),
  File "/usr/local/lib/python3.7/dist-packages/pelican/generators.py", line 97, in get_template
    self._templates[name] = self.env.get_template(name + ext)
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 494, in load
    return loader.load(environment, name, globals)
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/steve/work/github/egberts.github.io-src/m.css/egbert-theme/templates/cover.html", line 5, in template
    <title>{% output_file %}</title>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'output_file'.
make: *** [Makefile:47: html] Error 1
$ 
```

I've already added the following to `pelicanconf.py`:

```python
TEMPLATE_PAGES = { 'cover.html': 'blog/cover.html', }
```

Using Pelican 4.2, Jinja2 2.11.1

Notice to SO Moderators: All 3 Stackoverflow questions are focused on within the Jinja templating.  This question is focused on procurring these available variable from within HTML/Markdown using such much-needed Jinja coding within a Jinja2 template necessary to procur a valid list of available Jinja2 variables in HTML format so that it can be viewable from a web browser.

**Comment by bryanbrattlof** [comment]
Hi @egbert:

I haven't tested this yet (not by a computer with pelican right now) but
would ```{{ output_file }}``` fix the issue?

**Comment by egberts** [comment]
Yeah, your solution plus the missing `{% block block_name %}{{ page|e }} | {{ page.title|e }}{% endblock %}} partially fixed the problem and got me further...

I got this error on the 2nd generation pass.

```
-> Writing /home/steve/work/github/egberts.github.io-src/output/index.html
CRITICAL: UndefinedError: 'page' is undefined
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 570, in main
    pelican.run()
  File "/usr/local/lib/python3.7/dist-packages/pelican/__init__.py", line 137, in run
    p.generate_output(writer)
  File "/usr/local/lib/python3.7/dist-packages/pelican/generators.py", line 278, in generate_output
    override_output=True, url='')
  File "/usr/local/lib/python3.7/dist-packages/pelican/writers.py", line 278, in write_file
    override_output)
  File "/usr/local/lib/python3.7/dist-packages/pelican/writers.py", line 210, in _write_file
    output = template.render(localcontext)
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/steve/work/github/egberts.github.io-src/m.css/egbert-theme/templates/cover.html", line 28782, in top-level template code
    <meta itemprop="name" content="{% block xxitemprop_name %}{{ page|e }} | {{ page.settings['SITENAME'] }}{% endblock %}">
  File "/home/steve/work/github/egberts.github.io-src/m.css/egbert-theme/templates/cover.html", line 28782, in block "xxitemprop_name"
    <meta itemprop="name" content="{% block xxitemprop_name %}{{ page|e }} | {{ page.settings['SITENAME'] }}{% endblock %}">
  File "/home/steve/.local/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'page' is undefined
make: *** [Makefile:47: html] Error 1
```

**Comment by egberts** [comment]
It works with page.html and article.html template, but not the new cover.html template.

**Comment by avaris** [comment]
Are you including `cover.html` from `index.html`?

**Comment by avaris** [comment]
Oh, I think that's for `TEMPLATE_PAGES`... You might be confusing the purpose of that. `TEMPLATE_PAGES` is used to create HTML directly from a standalone jinja2 template. It's not associated with a page. That's why you get `page not defined` error.

If you made a page (`cover.md`) and set the `template` metadata for `cover`, then that page will be rendered using your `cover.html` template. You don't need a `TEMPLATE_PAGES`.

**Comment by justinmayer** [comment]
@egberts: Do you need any further assistance with this issue?

**Comment by egberts** [comment]
Thanks, we can close this issue.  I've resolved this by reading Jinja2 templating elsewhere.
