### ISSUE TITLE
[Feature Request] Full jinja debug information

### ISSUE THREAD

**Issue by Chaostheorie** [getpelican/pelican#2774]
I've  been creating themes and websites with pelican for various projects. The only problem that's been occurring and is very unpleasant and really hindering is the lack of debug information if an error occurs within the templates.

Example:
`WARNING: Caught exception "TemplateSyntaxError: unexpected '}'". Reloading.`

It would be nice if some kind of debug mode for jinja would be available to expose a full error trace of the jinja exception. This would a huge help when debugging and building themes.

Thanks in advance

**Comment by avaris** [comment]
I agree debug mode is useful. That's why there is already one in pelican: `--debug`. Did you try it? :)

**Comment by Chaostheorie** [comment]
Debug mode doesn't provide the (stack)trace

**Comment by avaris** [comment]
I am going to need a way to reproduce then:

```console
$ pelican content
CRITICAL: Encountered unknown tag 'extendz'.
$ pelican content --debug
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.8.2
[SKIP]
CRITICAL: Encountered unknown tag 'extendz'.
Traceback (most recent call last):
  File "/home/avaris/.venvs/p38/bin/pelican", line 11, in <module>
    load_entry_point('pelican', 'console_scripts', 'pelican')()
  File "/home/avaris/src/pelican/pelican/__init__.py", line 489, in main
    pelican.run()
  File "/home/avaris/src/pelican/pelican/__init__.py", line 121, in run
    p.generate_output(writer)
  File "/home/avaris/src/pelican/pelican/generators.py", line 686, in generate_output
    self.generate_pages(writer)
  File "/home/avaris/src/pelican/pelican/generators.py", line 597, in generate_pages
    self.generate_direct_templates(write)
  File "/home/avaris/src/pelican/pelican/generators.py", line 545, in generate_direct_templates
    write(save_as, self.get_template(template), self.context,
  File "/home/avaris/src/pelican/pelican/generators.py", line 97, in get_template
    self._templates[name] = self.env.get_template(name + ext)
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/loaders.py", line 426, in load
    return loader.load(environment, name, globals)
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/avaris/.venvs/p38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/avaris/ws/pt2/mytheme/templates/index.html", line 1, in template
    {% extendz "base.html" %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'extendz'.
```

**Comment by Chaostheorie** [comment]
Thank you for the advice. I dind't saw this cause I used `make` with `--debug`. Didn't saw that an environment variable is required instead.

**Comment by justinmayer** [comment]
@Chaostheorie: Yeahhhh... [As noted in the documentation](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help), the automation wrappers (including Make), are provided as a convenience and starting point and aren't supported in the same way `pelican` commands are.

**Comment by rr326** [comment]
@justinmayer - Unless I'm missing something in the docs, I think this is a bug. (Yes - I read the docs.) 

`pelican --debug` gives full debug information
`pelican --debug -r` gives full debug information
`pelican --debug -r -l` gives abbreviated debug information 

eg: 
```
-> Modified: settings, content, theme, images. re-generating...
           CRITICAL jinja2.exceptions.TemplateSyntaxError: expected token 'as', got 'end of statement block'                                                            __init__.py:552
```
