### ISSUE TITLE
Reader level cache results in TypeError with empty metadata in Markdown

### ISSUE THREAD

**Issue by avaris** [getpelican/pelican#2825]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Python version**: 3.8.2
- **Pelican version**: 4.5.3

## Issue

Metadata that should be discarded ([`_DISCARD`](https://github.com/getpelican/pelican/blob/8033162ba4393db60791b201fb100d1be0f04431/pelican/readers.py#L27-L31)) is stored in the cache and upon retrieval new `object()` instance is created and [fails filtration](https://github.com/getpelican/pelican/blob/8033162ba4393db60791b201fb100d1be0f04431/pelican/readers.py#L575).

Relevant information for reproducing is below. Note the empty `Tag:` metadata. First run is without cache and succeeds. Second run retrieves from cache and errors due to not being filtered.
```console
$ cat content/article.md
Title: asd
Tags:

Content here
$ cat pelicanconf.py
DEFAULT_DATE = 'fs'

CACHE_CONTENT = True
LOAD_CONTENT_CACHE = True
CONTENT_CACHING_LAYER= 'reader'
$ pelican content -s pelicanconf.py
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check https://docs.getpelican.com/en/latest/settings.html#TIMEZONE for more information
WARNING: Watched path does not exist: /home/avaris/ws/test/content/images
Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.11 seconds.
$ pelican content -s pelicanconf.py
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check https://docs.getpelican.com/en/latest/settings.html#TIMEZONE for more information
WARNING: Watched path does not exist: /home/avaris/ws/test/content/images
CRITICAL: 'object' object is not iterable
$ pelican content -s pelicanconf.py -D
DEBUG: Pelican version: 4.5.3
DEBUG: Python version: 3.8.2
[snip]
CRITICAL: 'object' object is not iterable
Traceback (most recent call last):
  File "/home/avaris/.venvs/ptest/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/home/avaris/.venvs/ptest/lib/python3.8/site-packages/pelican/__init__.py", line 523, in main
    pelican.run()
  File "/home/avaris/.venvs/ptest/lib/python3.8/site-packages/pelican/__init__.py", line 109, in run
    p.generate_context()
  File "/home/avaris/.venvs/ptest/lib/python3.8/site-packages/pelican/generators.py", line 659, in generate_context
    for tag in article.tags:
TypeError: 'object' object is not iterable

```

**Comment by jonasborges** [comment]
Hi @avaris, is this fix still wanted? 
I was looking into the code and it seems fairly easy to fix it. 

https://github.com/getpelican/pelican/blob/4.7.0/pelican/readers.py#L571-L575

From: 
```python
        content, reader_metadata = self.get_cached_data(path, (None, None))
        if content is None:
            content, reader_metadata = reader.read(path)
            self.cache_data(path, (content, reader_metadata))
        metadata.update(_filter_discardable_metadata(reader_metadata))
```

To:
```python
        content, reader_metadata = self.get_cached_data(path, (None, None))
        if content is None:
            content, reader_metadata = reader.read(path)
            reader_metadata = _filter_discardable_metadata(reader_metadata)  # discard before caching
            self.cache_data(path, (content, reader_metadata))
        metadata.update(reader_metadata)
```

I was wondering it's ok for me to submit a PR for it + unit tests covering that scenario.

**Comment by avaris** [comment]
Hi @jonasborges, yes this is still needed and you are more than welcome to submit a PR for it :). Thanks. Your suggested change is correct.
