### ISSUE TITLE
Cannot build my website

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican#2854]
Suddenly seems I cannot build anymore my site.
I receive strange messages referred to settings that are correctly set

- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Suddenly I cannot build anymore my website.
Launching the command <pelican> I receive strange messages relevant to settings that are - instead - properly set.
Launching <pelican --print-settings> the error messages are the same!
Terminal output here below:
(pelican-web) mau@Zurg:~/Sistema/pelican-web> pelican --print-settings
Feeds generated without SITEURL set properly may not be valid
No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check https://docs.getpelican.com/en/latest/settings.html#TIMEZONE for more information
Traceback (most recent call last):
  File "/home/mau/Sistema/pelican-web/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py", line 492, in main
    args = parse_arguments(argv)
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py", line 363, in parse_arguments
    args = parser.parse_args(argv)
  File "/usr/lib64/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py", line 224, in __call__
    instance, settings = get_instance(namespace)
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py", line 418, in get_instance
    return cls(settings), settings
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py", line 60, in __init__
    signals.initialized.send(self)
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/plugins/seo/seo.py", line 33, in plugin_initializer
    to use SEO plugin."
Exception: You must fill in SITEURL variable in pelicanconf.py             to use SEO plugin.

In my pelicanconf.py
TIMEZONE = 'UTC'
and SEO plugin has been commented out...

**Comment by mpaglia0** [comment]
Solved.
I was calling command from the wrong directory
