### ISSUE TITLE
Pelican import fails on tumblr blog entry

### ISSUE THREAD

**Issue by boxydog** [getpelican/pelican#3177]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: OS X 12.6.7
- **Python version**: 3.11.4
- **Pelican version**: 4.8.0
- **Link to theme**: n/a
- **Links to plugins**: n/a
- **Link to your site**: n/a
- **Link to your source**: n/a
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: n/a

## Issue

Ran:

> pelican-import --tumblr -o boxydog --blogname=boxydog my-api-key

Crashes on an entry in 2016:

```
Traceback (most recent call last):
  File "/Users/.../.venv/bin/pelican-import", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/pelican/tools/pelican_import.py", line 1019, in main
    fields2pelican(fields, args.markup, args.output,
  File "/Users/.../.venv/lib/python3.11/site-packages/pelican/tools/pelican_import.py", line 784, in fields2pelican
    for (title, content, filename, date, author, categories, tags, status,
  File "/Users/.../.venv/lib/python3.11/site-packages/pelican/tools/pelican_import.py", line 505, in tumblr2fields
    players = '\n'.join(player.get('embed_code')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, bool found
```

I bet it's this entry: https://www.tumblr.com/boxydog/148936576299/two-opposite-personalities-one-driven-to-big

It looks to have a broken youtube embed.

**Comment by boxydog** [comment]
Thanks so much.
