### ISSUE TITLE
Importing xml from wordpress

### ISSUE THREAD

**Issue by nopp** [getpelican/pelican#877]
Hi folks, 

I try import xml from wordpress, but doesn't work:

carlos@malucelli:~/projetos/teste$ pelican-import --wpfile -o ./content/ /home/carlos/Downloads/carlosmalucellcom.wordpress.2013-05-07.xml 
Traceback (most recent call last):
  File "/usr/local/bin/pelican-import", line 9, in <module>
    load_entry_point('pelican==3.3', 'console_scripts', 'pelican-import')()
  File "/usr/local/lib/python2.7/dist-packages/pelican-3.3-py2.7.egg/pelican/tools/pelican_import.py", line 516, in main
    disable_slugs=args.disable_slugs or False)
  File "/usr/local/lib/python2.7/dist-packages/pelican-3.3-py2.7.egg/pelican/tools/pelican_import.py", line 367, in fields2pelican
    for title, content, filename, date, author, categories, tags, in_markup in fields:
  File "/usr/local/lib/python2.7/dist-packages/pelican-3.3-py2.7.egg/pelican/tools/pelican_import.py", line 117, in wp2fields
    if item.find('status').string == "publish":
AttributeError: 'NoneType' object has no attribute 'string'

Can help me with this ?

**Comment by danielhoherd** [comment]
I am experiencing this problem and am trying to debug it. Curiously, I am able to work around it and cause it in various ways.

The problem I found in the directly exported xml file that WordPress created was there was an 09 0a 09 sequence, which appears to be a tab followed by a malformed tab, which is not UTF-8 compliant.  Is that correct?  Strangely, by removing entries prior to this one, and leaving that string in, it succeeded.  Removing all tabs caused the problem to occur on an earlier entry that previously had not experienced the problem.
